### ISSUE TITLE
Version 0.2.1 breaks glfw

### ISSUE THREAD

**Issue by cwds** [rust-lang/bitflags#10]
glfw v0.0.8 has a dependancy on bitflags.  Version 0.1.1 of bitflags is fine, 0.2.1 gives this error in the build:

   Compiling glfw v0.0.8
<bitflags macros>:8:24: 15:4 error: conflicting implementations for trait `core::fmt::Debug` [E0119]
<bitflags macros>:8 bits : $ value } ; ) + impl :: std:: fmt:: Debug for $ BitFlags {
<bitflags macros>:9 fn fmt ( & self , f : & mut :: std:: fmt:: Formatter ) -> :: std:: fmt::
<bitflags macros>:10 Result {
<bitflags macros>:11 let mut first = true ; $ (
<bitflags macros>:12 if self . contains ( $ Flag ) {
<bitflags macros>:13 if ! first { try ! ( f . write_str ( " | " ) ) ; } first = false ; try ! (
                     ...
<bitflags macros>:1:1: 79:67 note: in expansion of bitflags!
/Users/chris/.cargo/registry/src/github.com-1ecc6299db9ec823/glfw-0.0.8/src/lib.rs:1041:1: 1049:2 note: expansion site
/Users/chris/.cargo/registry/src/github.com-1ecc6299db9ec823/glfw-0.0.8/src/lib.rs:1051:1: 1063:2 note: note conflicting implementation here
/Users/chris/.cargo/registry/src/github.com-1ecc6299db9ec823/glfw-0.0.8/src/lib.rs:1051 impl fmt::Debug for Modifiers {
/Users/chris/.cargo/registry/src/github.com-1ecc6299db9ec823/glfw-0.0.8/src/lib.rs:1052     fn fmt(&self, f: &mut fmt::Formatter) -> fmt::Result {
/Users/chris/.cargo/registry/src/github.com-1ecc6299db9ec823/glfw-0.0.8/src/lib.rs:1053         for (i, x) in [Shift, Control, Alt, Super].iter().filter(|x| self.contains(**x)).enumerate() {
/Users/chris/.cargo/registry/src/github.com-1ecc6299db9ec823/glfw-0.0.8/src/lib.rs:1054             if i != 0 { try!(write!(f, ", ")) };
/Users/chris/.cargo/registry/src/github.com-1ecc6299db9ec823/glfw-0.0.8/src/lib.rs:1055             if      *x == Shift   { try!(write!(f, "Shift"   )) }
/Users/chris/.cargo/registry/src/github.com-1ecc6299db9ec823/glfw-0.0.8/src/lib.rs:1056             else if *x == Control { try!(write!(f, "Control" )) }
                                                                                        ...
error: aborting due to previous error

Compiling anything with glfw should produce this error.  Pulling up the previous version with

cargo update -p bitflags --precise 0.1.1

has everything running again.  This conflict with bitflags only occurs in an OSX build, not Linux.

**Comment by alexcrichton** [comment]
This was indeed a breaking change! This is why Cargo recommends using semver as the change from 0.1.0 to 0.2.0 was a signal for this breaking change. Dependencies on `bitflags` should declare something like `0.1.0` instead of `*` because no breaking changes will be made to the `0.1.0` track, but future tracks will include breaking changes.

**Comment by cwds** [comment]
Thanks for the reply, but this sort of breakage is what makes Rust so problematic in it's current form; if you can't rely on simple functionality like this in the library, it is almost impossible to build on top of it.  It's fine that much of this stuff was taken out of the core distribution, but many of these libraries are needed to do anything useful - particularly with packages like num.

In this case I was not using bitflags directly; it's being called by glfw, and even then apparently only on one platform.  So there is no clean way to fix this without fiddling with the glfw repository, or relying on a forked version of all of these libraries.

Perhaps depreciating (or at least discouraging through warnings) the "*" option in cargo is a path forward.  In such a way dependancies can be updated by the package (crate?) maintainers as they see fit.

**Comment by alexcrichton** [comment]
Changes like this are completely orthogonal to Rust as a language. For quite some time now Cargo and Rust have been advertised as following semver, and this change fits *exactly* within those guidelines. The movement from 0.1.0 to 0.2.0 is a clear message that a breaking change was made. Crates which depend on `*` are opting in picking up future breaking changes automatically, and it is **strongly discouraged**.

Adding a warning for `*` dependencies to Cargo is possible, but discussion should happen on the rust-lang/cargo repo, probably not here.
