### ISSUE TITLE
Namespaced bitflag constants?

### ISSUE THREAD

**Issue by nukep** [rust-lang/bitflags#5]
Would there be any objection to putting all generated consts in a module named after the type? This way, they could behave more like how enums do with variants globbing. It would also prevent documentation clutter in rustdoc, where all the constants are currently listed indiscriminately in the parent module.

Should we allow non-caps in constants so that they're stylistically closer to enums?

The syntax seems to work: http://is.gd/hGgTe7

**Comment by alexcrichton** [comment]
Thanks for the report! These are actually more appropriate as associated constants, which have no recently landed in the nightly compiler, and this library can switch to using them in the future as soon as they're stable!
