### ISSUE TITLE
Explicit dependency on std

### ISSUE THREAD

**Issue by jdub** [rust-lang/bitflags#6]
I notice that some freestanding folk are borrowing this code, doing a quick `s#::std#::core#` and going on their merry way.

`core` isn't stable, so I can't suggest you do that, but… I wonder if there's a solution on the horizon for this explicit module dependency problem. I imagine it's going to pop up more and more often as people do *fun* things with Rust.

Thoughts?

**Comment by alexcrichton** [comment]
For now the dependency on std is due to the fact that this library needs to build on stable Rust. As soon as we have a stable libcore, though, this'll move to using it!

**Comment by jdub** [comment]
Now that's a future to look forward to… thank you!
