### ISSUE TITLE
New Debug impl fails to compile when the bitflags are conditional

### ISSUE THREAD

**Issue by CraZySacX** [rust-lang/bitflags#8]
The following code cause a compilation error when compiled not compiled with feature "C".

```rust
bitflags! {
    flags Flags: u32 {
        const FLAG_A = 0b00000001,
        const FLAG_B  = 0b00000010,
        #[cfg(feature = "C")] const FLAG_C = 0b00000100,
    }
}
```

> <bitflags macros>:12:22: 12:28 error: unresolved name `FLAG_C`
> <bitflags macros>:12 if self . contains ( $ Flag ) {
>                                           ^~~~~~
> <bitflags macros>:1:1: 79:67 note: in expansion of bitflags!
> <bitflags macros>:77:1: 79:63 note: expansion site
> <bitflags macros>:1:1: 79:67 note: in expansion of bitflags!

**Comment by alexcrichton** [comment]
Fixed in #9
